# Generated by Django 4.1.5 on 2023-01-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='ghjfg', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
